python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00000500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00001000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00001500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00002000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00002500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00003000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00003500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00004000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00004500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00005000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00005500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00006000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00006500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00007000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00007500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00008000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00008500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00009000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00009500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00010000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00010500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00011000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00011500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00012000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00012500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00013000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00013500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00014000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00014500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00015000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00015500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00016000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00016500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00017000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00017500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00018000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00018500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00019000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00019500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00020000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00020500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00021000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00021500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00022000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00022500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00023000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00023500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00024000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00024500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00025000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00025500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00026000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00026500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00027000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00027500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00028000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00028500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00029000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00029500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00030000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00030500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00031000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00031500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00032000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00032500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00033000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00033500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00034000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00034500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00035000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00035500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00036000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00036500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00037000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00037500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00038000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00038500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00039000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00039500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00040000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00040500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00041000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00041500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00042000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00042500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00043000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00043500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00044000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00044500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00045000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00045500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00046000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00046500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00047000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00047500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00048000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00048500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00049000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00049500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00050000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00050500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00051000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00051500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00052000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00052500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00053000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00053500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00054000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00054500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00055000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00055500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00056000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00056500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00057000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00057500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00058000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00058500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00059000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00059500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00060000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00060500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00061000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00061500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00062000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00062500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00063000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00063500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00064000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00064500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00065000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00065500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00066000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00066500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00067000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00067500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00068000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00068500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00069000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00069500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00070000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00070500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00071000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00071500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00072000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00072500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00073000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00073500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00074000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00074500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00075000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00075500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00076000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00076500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00077000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00077500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00078000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00078500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00079000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00079500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00080000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00080500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00081000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00081500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00082000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00082500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00083000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00083500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00084000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00084500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00085000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00085500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00086000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00086500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00087000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00087500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00088000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00088500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00089000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00089500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00090000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00090500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00091000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00091500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00092000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00092500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00093000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00093500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00094000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00094500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00095000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00095500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00096000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00096500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00097000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00097500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00098000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00098500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00099000.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00099500.pt --output_folder test_out_April_14/ --a2b 1
python test.py --config configs/example.yaml --input test_in_April_14/ --checkpoint outputs/example/checkpoints/gen_00100000.pt --output_folder test_out_April_14/ --a2b 1
dir